# Define el alias para que /codeigniter apunte a la carpeta public
Alias /codeigniter "/var/www/html/codeigniter/project-root/public"

<Directory "/var/www/html/codeigniter/project-root/public">
    Options Indexes FollowSymLinks
    AllowOverride All
    Require all granted
</Directory>
